containter_additem(0, item.sword, 1, -1, 0);
containter_additem(1, item.sawedoff, 1, -1, 0);
containter_additem(2, item.bullet45acp, 10, -1, 0);
containter_additem(3, item.sneakers, 1, -1, 0);
containter_additem(4, item.sneakers, 1, -1, 0);
containter_additem(5, item.sneakers, 1, -1, 0);
containter_additem(6, item.sneakers, 1, -1, 0);
containter_additem(7, item.sneakers, 1, -1, 0);
containter_additem(8, item.apple, 10, -1, 0);